version: '3'

volumes:
    logs:
        driver: local

services:
    web:
        image: php:7-alpine
        working_dir: /var/www/html
#        command: php -S 0.0.0.0:5000 -t public
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        depends_on:
            - php
            - mysqldb
        ports:
            - 8080:5000
            - 5000:80
        volumes:
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./etc/ssl:/etc/ssl
            - .:/var/www/html
            - ./logs:/var/www/logs
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        ports:
          - "2222:22" # ssh
        environment:
                PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
                XDEBUG_CONFIG: remote_host=10.254.254.254
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - .:/var/www/html
    composer:
        image: "composer"
        volumes:
            - ".:/app"
        command: install
    mysqldb:
        image: mysql
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${dbname}
            - MYSQL_ROOT_PASSWORD=${dbrootuser}
            - MYSQL_USER=${dbuser}
            - MYSQL_PASSWORD=${dbpass}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
