<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PodcastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobleadsRepository extends EntityRepository
{
    public function findByExampleField($value)
    {
        return $this->createQueryBuilder('j')
          ->andWhere('c.exampleField = :val')
          ->setParameter('val', $value)
          ->orderBy('j.id', 'ASC')
          ->setMaxResults(10)
          ->getQuery()
          ->getResult()
          ;
    }

}
